# /Volumes/Crucial X8/Programming/UAEW_app/uaewapp_1/.streamlit/secrets.toml

# O nome da seção [gcp_service_account] deve ser exatamente este,
# pois é o que seu código em utils.py está procurando.
[gcp_service_account]
type = "service_account"
project_id = "uae-warriors-app"
private_key_id = "96b8e2c735ffe11028c447de4644cd72343e9d88"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDE3OJ4Cb2vAkVz
HV8y/m5WW7rxTdBvze5umyhnwpDwhM1v3pWjGdt7qb9WxXMjSQeN1xGmQYtREOFH
S9rPg9WxuH+RarWYRCsibEF3iIS95PmD1JEByqHOQvM2tAufeCOyngwi4+gth0Yb
BtBPH8xq1IhYU8XePPCRk2U/Aa+zpi6zL+5hmGyI1QBXOe41KRH+Q6ZqN8YcUC/e
OZWHoemMmmL5F/nZ2Nc2atnNZob2IoW4UJpEZaR2bMYjMPSYjO+aXh0/JPJEmBw5
63gz+foy/3jXGvn/RcOvH8gO+lw8DO87MveFTrVYJfm9gLiH8jlnWFwswdDr9e6g
Z8Tfi/XbAgMBAAECggEAAqIDo2BZ+Ze5rw7zAX8WobALYYPNaFlkOXV4xl57SsQz
7S2YabyES3SbOwFcB1pIMBTyxvr0boqfwLDahdD5EC3sAtlfAWDUBNtWys74G4QO
9DzpDZGUtWn+z7n7t8/HBnIHroXGyqkW/nCKY6yEst8RzcCdElpVS1Uh0wRmQaxO
wyhtl0FdZiWTRYkiBEmfjemNfeHe6V+D55bFR71J0N3Hh21Uum2q/hrdZt/5EszX
U6BokajTAE84ttNWujezPNCqNc/TpIVhr7ybYl09obHKwnWdPCufUDgN93kQDSPB
uES6CPsRghU2s8LIFu4iViEyXrkaaleSoLNu1H20/QKBgQD721ecwBK5PNyFCLpP
huJ0qtdUuHp08un+PKcnLAJVqYIyivKQZo/CqD4pDwt8zS0qtYOG7lGPQfsaA+93
RAIhv4Sro2tr/8mgdKux0ocDKbusg/DHNkusDD9cRBlkRNJKdqrceUY08ugEChpl
B+crcqU/RLZyl7CKyQY6n6JvpQKBgQDIGfGCpS+j9avWQRdV1RSSEh0yK21Zj3/Q
ohrdx6tj8TtqDc2+ziZY0foDnyP/25WqUUynQA7stsne7bv/bmlgCCYa3r6Aw47l
wfNc85gPJqPnHzaN+Vs16XNHRo/pcvojFLiAMF2kts+eq8+D7AtEycFsqkd+nnXh
75rsQvfXfwKBgHemof3fJkYIiv9MwS6M90LT8w7VwZ+T0+SrrgGnH8jQigE3D7vY
bc3dngJlmmCFHUMgDsdoqyizAPdADWEM1zJvSTk9nwgk8gYfx33odankBrwTxqzt
t4+aFfPgimufYoRr0gqCNv9qsx1QK2/6DDIQ+j6Ph1nzhLS6ghIRytrdAoGBAJvh
igDKijhiM8Eu5+zXl7TLI69noUH5xgpTnjZTS7MJw800f6k6kyjyOqADo1m4R/ls
aBiKkJXbN5vQ+3lbG//RmU2pZCKPNYzK8LjikvyKj3iHGkqzjFiNSl6mG4ozJaWa
iLhj9S9Rsp/bHEea5JRrz6DFbfi3nQGrVLbk3IolAoGAQV+hiR46YDbv4PDD37hf
PETcnVnrWXoOya7C2IWhF7tc7/vy1i+54sZ1iM789JGjHfd++upsdXxnZ/Qp+hCr
cMv5CowFCD58rnd5cabc/1BIcqcGj8wizfoWgjs/FpE95e0xOB4bFdjxyGiV49TR
xMLUqQEIdX3mIKHJzgJ2b+8=
-----END PRIVATE KEY-----"""
client_email = "uae-warriors-app@uae-warriors-app.iam.gserviceaccount.com"
client_id = "112017814632835878172"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/uae-warriors-app%40uae-warriors-app.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
